<a href="https://colab.research.google.com/github/sparsh2002/Complete_Machine_Learning/blob/master/Python-Basics/4_Numpy_and_inbuilt_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy


In [1]:
import numpy as np

In [3]:
my_lst = [1,2,3,4]
arr =np.array(my_lst)

In [4]:
type(arr)

numpy.ndarray

In [5]:
print(arr)

[1 2 3 4]


In [6]:
arr.shape

(4,)

In [7]:
arr

array([1, 2, 3, 4])

In [8]:
my_lst1 = [1,2,3,4]
my_lst2 = [5,6,7,8]
my_lst3 = [9,10,11,12]

In [9]:
arr = np.array([my_lst1 , my_lst2 , my_lst3])

In [10]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
arr.shape

(3, 4)

In [12]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

## Indexing

In [14]:
arr[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
arr[1:2]

array([[5, 6, 7, 8]])

In [16]:
arr[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
arr[0:2 ,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr[:,3:]

array([[ 4],
       [ 8],
       [12]])

In [19]:
arr = np.arange(0,10)

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr[3:] = 100

In [22]:
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [23]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [24]:
arr<2

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [25]:
arr[arr<2]

array([0, 1])

In [26]:
np.ones(4)

array([1., 1., 1., 1.])

In [28]:
np.ones((5,2) , dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [29]:
np.random.rand(3,3)

array([[0.73948212, 0.52871373, 0.14529511],
       [0.22455739, 0.5333719 , 0.37572355],
       [0.50042747, 0.35495792, 0.69727194]])

In [30]:
np.random.randn(3,3)

array([[-1.00558525,  0.22524462, -0.48893775],
       [ 0.73808547, -0.65189501, -0.34933263],
       [ 0.07390409, -0.40742656, -0.23550104]])